environment:
  matrix:
    - node_version: '10.14'
    - node_version: '12'
    - node_version: '14'
branches:
  only:
    - master
install:
  - ps: Install-Product node $env:node_version
  - npm install
test_script: npm run validate
cache:
  - ~/.npm
build: off
