branches:
  only:
  - master

environment:
  nodejs_version: 6

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm t

build: off
